name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'   # dispara quando você cria tags tipo v1.0.0

permissions:
  contents: read
  id-token: write   # necessário para npm provenance (se "publishConfig.provenance": true)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --provenance
